[package]
name = "d20_dice_roller"
version = "0.2.0"
authors = ["void <theprismaticvoid@gmail.com>"]
license = "MIT/Apache-2.0"

[features]
default = []

external_token = []

[profile.release]
lto = true

[dependencies]
serenity = "0.5.4"
rand = "0.4"
